name: "DevSecOps Full Security Pipeline"

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  # 1. SEMGREP : Analyse du Code (SAST)
  semgrep-sast:
    name: Code Scan (Semgrep)
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Semgrep Scan
        run: |
          docker run --rm -v "${{ github.workspace }}:/src" semgrep/semgrep semgrep scan \
          --config=p/python \
          --sarif \
          --output=/src/report-semgrep.sarif \
          /src
        continue-on-error: true

      - name: Upload Semgrep SARIF
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: report-semgrep.sarif

  # 2. GITLEAKS : Détection des Secrets
  gitleaks-secrets:
    name: Secrets Scan (Gitleaks)
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true


  # 3. TRIVY : Scan de l'image Docker (CVE)
  trivy-container:
    name: Container Scan (Trivy)
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t mon-app-vulnerable:latest .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: 'mon-app-vulnerable:latest'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
        continue-on-error: true

      - name: Upload Trivy SARIF
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: trivy-results.sarif